### ISSUE TITLE
dev-util/electron with bundled-openssl

### ISSUE THREAD

**Issue by soredake** [csmk/frabjous#1]
like in https://github.com/gentoo/gentoo/pull/2715/files

**Comment by csmk** [comment]
I'll look into it. But instead of pushing old versions, I'll try to push the version 1.3.13. Although, Node 6.5.0 seems to be bundled with OpenSSL 1.0.2h, this is really ok for you?

**Comment by soredake** [comment]
Since i use libressl, in any case, i have to use the bundled openssl. So it's ok for me.

>I'll try to push the version 1.3.13
Not sure that this version is compatible with app-editors/atom.

**Comment by csmk** [comment]
> So it's ok for me.

Ok then.

> Not sure that this version is compatible with app-editors/atom.

Seems compatible, see https://github.com/gentoo/gentoo/blob/60deb5cf5ced4e641e8d6dbf01633083efb17509/app-editors/atom/atom-1.12.2.ebuild#L94

**Comment by soredake** [comment]
@csmk seems, but not tested, i'll try atom with 1.3.13 version after you push it.

**Comment by csmk** [comment]
I've successfully build 1.3.6 and 1.3.13, so I'll push both versions.

**Comment by soredake** [comment]
Very very thanks!

**Comment by csmk** [comment]
If you have interest in becoming collaborator, write me an email, ok. My public key you can find [here](https://keybase.io/csmk).

Closing the issue, cheers!

**Comment by csmk** [comment]
@soredake do you still have interest in this package? I'm asking because I'm thinking to remove it, as I don't use it for quite some time.

I saw that you started your own overlay, so you could adopt it if you want.

**Comment by soredake** [comment]
I dont use nodejs/electron anymore.
