### ISSUE TITLE
chronograf-1.5.0.0.tar.gz checksum failure

### ISSUE THREAD

**Issue by babykart** [csmk/frabjous#104]
Hi,

chronograf-1.5.0.0 fails to emerge due to checksum failure. 

```
!!! Fetched file: chronograf-1.5.0.0.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      4643073
!!! Expected: 4639964
```

**Comment by csmk** [comment]
Thanks for let me know, I'll fix it shortly.

**Comment by csmk** [comment]
If you use OpenRC, keep in mind that I did some improvements in the init script (following upstream changes), so you might need to reconfigure your `/etc/conf.d/chronograf`.

**Comment by babykart** [comment]
@csmk thx for the information... and the quick fix...
