### ISSUE TITLE
net-im/dino depends on >=dev-lang/vala-0.30

### ISSUE THREAD

**Issue by minami-o** [csmk/frabjous#65]
Hi there,
Thanks for the overlay!
Just tried to emerge dino, and it failed at source config with the following error:
```
-- Performing Test COMPILER_SUPPORTS_Wno_unused_label - Success
-- Found PkgConfig: x86_64-pc-linux-gnu-pkg-config (found version "0.29.2")
-- Found GObject: /usr/lib/libgobject-2.0.so (found version "2.50.3")
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):  
  Could NOT find Vala (missing: VALA_EXECUTABLE) (Required is at least
  version "0.30")  
Call Stack (most recent call first):  
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)  
  cmake/FindVala.cmake:67 (find_package_handle_standard_args)
  CMakeLists.txt:124 (find_package)
```
Installing vala (0.32) solved the issue, so I guess adding vala>0.30 in the dependencies of the ebuild should do.
Cheers

**Comment by csmk** [comment]
Hi,
Thank you for reporting the issue. You're correct, I made the mistake to not add `$(vala_depend)` (from vala.eclass) in the dependencies, which does the same you commented above. I'll fix it in the next commit.
