### ISSUE TITLE
dev-deb/influxdb-1.4.2

### ISSUE THREAD

**Issue by DefauIt** [csmk/frabjous#78]
```
 * Package:    dev-db/influxdb-1.4.2
 * Repository: frabjous
 * Maintainer: csmk+frabjous@chaoslab.org
 * Upstream:   https://github.com/influxdata/influxdb/issues
 * USE:        amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Vendoring collectd.org github.com-collectd-go-collectd-e84e8af.tar.gz
 * Vendoring github.com/BurntSushi/toml github.com-BurntSushi-toml-a368813.tar.gz
 * Vendoring github.com/bmizerany/pat github.com-bmizerany-pat-c068ca2.tar.gz
 * Vendoring github.com/boltdb/bolt github.com-boltdb-bolt-4b1ebc1.tar.gz
 * Vendoring github.com/cespare/xxhash github.com-cespare-xxhash-1b6d2e4.tar.gz
 * Vendoring github.com/davecgh/go-spew github.com-davecgh-go-spew-346938d.tar.gz
 * Vendoring github.com/dgrijalva/jwt-go github.com-dgrijalva-jwt-go-24c63f5.tar.gz
 * Vendoring github.com/dgryski/go-bitstream github.com-dgryski-go-bitstream-7d46cd2.tar.gz
 * Vendoring github.com/gogo/protobuf github.com-gogo-protobuf-1c2b16b.tar.gz
 * Vendoring github.com/golang/snappy github.com-golang-snappy-d9eb7a3.tar.gz
 * Vendoring github.com/google/go-cmp github.com-google-go-cmp-18107e6.tar.gz
 * Vendoring github.com/influxdata/influxql github.com-influxdata-influxql-3921ab7.tar.gz
 * Vendoring github.com/influxdata/usage-client github.com-influxdata-usage-client-6d38953.tar.gz
 * Vendoring github.com/influxdata/yamux github.com-influxdata-yamux-1f58ded.tar.gz
 * Vendoring github.com/influxdata/yarpc github.com-influxdata-yarpc-036268c.tar.gz
 * Vendoring github.com/jwilder/encoding github.com-jwilder-encoding-2789473.tar.gz
 * Vendoring github.com/paulbellamy/ratecounter github.com-paulbellamy-ratecounter-5a11f58.tar.gz
 * Vendoring github.com/peterh/liner github.com-peterh-liner-8860952.tar.gz
 * Vendoring github.com/philhofer/fwd github.com-philhofer-fwd-1612a29.tar.gz
 * Vendoring github.com/retailnext/hllpp github.com-retailnext-hllpp-38a7bb7.tar.gz
 * Vendoring github.com/tinylib/msgp github.com-tinylib-msgp-ad0ff2e.tar.gz
 * Vendoring github.com/uber-go/atomic github.com-uber-go-atomic-74ca5ec.tar.gz
 * Vendoring github.com/uber-go/zap github.com-uber-go-zap-fbae028.tar.gz
 * Vendoring github.com/xlab/treeprint github.com-xlab-treeprint-06dfc6f.tar.gz
 * Vendoring golang.org/x/crypto github.com-golang-crypto-9477e0b.tar.gz
 * Vendoring golang.org/x/sys github.com-golang-sys-062cd7e.tar.gz
 * Vendoring golang.org/x/text github.com-golang-text-a71fd10.tar.gz
>>> Source unpacked in /var/tmp/portage/dev-db/influxdb-1.4.2/work
>>> Preparing source in /var/tmp/portage/dev-db/influxdb-1.4.2/work/influxdb-1.4.2/src/github.com/influxdata/influxdb ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-db/influxdb-1.4.2/work/influxdb-1.4.2/src/github.com/influxdata/influxdb ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-db/influxdb-1.4.2/work/influxdb-1.4.2/src/github.com/influxdata/influxdb ...
pkg/bits/bits.go:6:2: cannot find package "github.com/dgryski/go-bits" in any of:
	/var/tmp/portage/dev-db/influxdb-1.4.2/work/influxdb-1.4.2/src/github.com/influxdata/influxdb/vendor/github.com/dgryski/go-bits (vendor tree)
	/usr/lib/go/src/github.com/dgryski/go-bits (from $GOROOT)
	/var/tmp/portage/dev-db/influxdb-1.4.2/work/influxdb-1.4.2/src/github.com/dgryski/go-bits (from $GOPATH)
 * ERROR: dev-db/influxdb-1.4.2::frabjous failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 115:  Called src_compile
 *   environment, line 1369:  Called die
 * The specific snippet of code:
 *       go install -v -ldflags "${GOLDFLAGS}" ./cmd/influx{,d,_stress,_inspect,_tsm} || die;
 * 
 * If you need support, post the output of `emerge --info '=dev-db/influxdb-1.4.2::frabjous'`,
 * the complete build log and the output of `emerge -pqv '=dev-db/influxdb-1.4.2::frabjous'`.
 * The complete build log is located at '/var/tmp/portage/dev-db/influxdb-1.4.2/temp/build.log.gz'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-db/influxdb-1.4.2/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-db/influxdb-1.4.2/work/influxdb-1.4.2/src/github.com/influxdata/influxdb'
 * S: '/var/tmp/portage/dev-db/influxdb-1.4.2/work/influxdb-1.4.2/src/github.com/influxdata/influxdb'

```

**Comment by DefauIt** [comment]
Can't locate dgryski/go-bits, why does it commented

**Comment by DefauIt** [comment]
`Portage 2.3.2 (python 2.7.12-final-0, funtoo/1.0/linux-gnu/arch/pure64, gcc-5.3.0, glibc-2.23-r4, 4.9.34-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.9.34-gentoo-x86_64-Intel-R-_Core-TM-_i7-6700_CPU_@_3.40GHz-with-gentoo-2.2.1
KiB Mem:    32691512 total,  28277992 free
KiB Swap:   33511464 total,  33511464 free
sh bash 4.3_p48
ld GNU ld (Funtoo 2.25) 2.25.0
app-shells/bash:          4.3_p48::gentoo
dev-lang/perl:            5.22.2::gentoo
dev-lang/python:          2.7.12::gentoo, 3.4.5::gentoo
dev-util/cmake:           3.7.2::gentoo
sys-apps/baselayout:      2.2.1::gentoo
sys-apps/openrc:          0.23.2::gentoo
sys-apps/sandbox:         2.10-r3::gentoo
sys-devel/autoconf:       2.69::gentoo
sys-devel/automake:       1.13.4::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25-r2::gentoo
sys-devel/gcc:            5.3.0-r1::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.9::gentoo (virtual/os-headers)
sys-libs/glibc:           2.23-r4::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: git
    sync-uri: git://github.com/funtoo/ports-2012.git
    priority: -1000

frabjous
    location: /var/lib/layman/frabjous
    sync-type: laymansync
    sync-uri: https://github.com/csmk/frabjous.git
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=broadwell -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/easy-rsa /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php7.0/ext-active/ /etc/php/cgi-php7.0/ext-active/ /etc/php/cli-php7.0/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=broadwell -O2 -pipe"
DISTDIR="/usr/portage/distfiles"
FEATURES="assume-digests binpkg-logs candy compress-build-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch prelink-checksums preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=broadwell -O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org https://distmirror.ceresia.ch:81 https://distfiles.ceresia.ch"
INSTALL_MASK="/etc/systemd/ /usr/lib/systemd/ /lib/systemd/"
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed"
LINGUAS="en_US en ru ru_RU"
MAKEOPTS="-j8"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_TMPDIR="/var/tmp"
USE="acl amd64 bcmath berkdb bzip2 cgi cli cracklib cron crypt ctype curl cxx exif fileinfo filter fpm gd gdbm hash iconv icu imap intl ipv6 json libmysqlclient mhash mmx modules mudflap mysql mysqli ncurses nls nptl opcache openmp pam pcre pdo perl phar php posix python readline resolvconf session simplexml soap sockets sqlite sse sse2 ssl suexec tcpd threads tidy tokenizer truetype udev unicode webp xattr xfs xml xmlreader xmlrpc xmlwriter xslt zip zlib" ABI_X86="64" APACHE2_MODULES="actions asis alias auth_basic authn_core authz_core authz_host autoindex cache cgi cgid dav dav_fs dav_lock deflate dir env expires ext_filter file_cache filter headers include info log_config logio mime mime_magic negotiation rewrite socache_shmcb status unique_id unixd userdir usertrack vhost_alias access_compat auth_digest cache_disk cache_socache charset_lite dumpio http2 ident imagemap log_forensic macro proxy proxy_fcgi proxy_html proxy_http proxy_scgi ratelimit remoteip reqtimeout slotmem_shm version" APACHE2_MPMS="worker" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" COLLECTD_PLUGINS="aggregation cgroups conntrack cpu cpufreq cpusleep curl curl_json dbi df disk exec fhcount interface ipc load logfile mbmon md memory modbus mysql entropy netlink network nginx notify_email ntpd openvpn perl processes protocols swap smart sensors syslog tail tcpconns thermal threshold unixsock uptime users vmem write_graphite write_log" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64 pc" INPUT_DEVICES="evdev synaptics keyboard mouse" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="en_US en ru ru_RU" NGINX_MODULES_EXTERNAL="accept_language cache_purge concat dav_ext encrypted_session fancyindex headers_more metrics naxsi rtmp sticky upload_progress upstream_check ndk" NGINX_MODULES_HTTP="fastcgi access addition auth_basic auth_request autoindex browser charset dav degradation flv geo geoip gunzip gzip gzip_static image_filter limit_conn limit_req map mp4 perl proxy random_index realip referer rewrite scgi secure_link split_clients ssi ssl stub_status sub upstream_hash upstream_ip_hash upstream_keepalive upstream_least_conn upstream_zone userid xslt" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-0" POSTGRES_TARGETS="postgres9_5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" QEMU_SOFTMMU_TARGETS="i386 x86_64" QEMU_USER_TARGETS="i386 x86_64" RUBY_TARGETS="ruby21 ruby22 ruby23 ruby24" USERLAND="GNU" VIDEO_CARDS="intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CPPFLAGS, CTARGET, EMERGE_DEFAULT_OPTS, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS
`

**Comment by csmk** [comment]
> Can't locate dgryski/go-bits, why does it commented

Strange, on my machines it build fine without it. Although in 1.3.x series it was necessary. Anyway, I will fix in the next commit. Thanks for the report.

**Comment by csmk** [comment]
Please sync the repo and reemerge again. It should be fixed now.

**Comment by DefauIt** [comment]
All fine! Thnx! Compilled!
