### ISSUE TITLE
manifest-hashes missing in metadata/layout.conf

### ISSUE THREAD

**Issue by twam** [csmk/frabjous#79]
emerge --sync complains about a missing manifest-hashes:

> /usr/lib64/python3.6/site-packages/portage/repository/config.py:1061: SyntaxWarning: Repository named 'frabjous' specifies 'manifest-required-hashes' setting without corresponding 'manifest-hashes'. Portage will default it to match the required set but please add the missing entry to: /usr/local/overlay/frabjous/metadata/layout.conf

**Comment by csmk** [comment]
Hi,

I think it should've been fixed in https://github.com/csmk/frabjous/pull/75. Please could you try `emerge --sync` again and see if the warning still shows up?

**Comment by twam** [comment]
The trick is to do it twice, as only then the new layout.conf is actually parsed on ``emerge --sync``. Sorry for the confusion.
