### ISSUE TITLE
dev-libs/libstrophe-0.9.2

### ISSUE THREAD

**Issue by pasis** [csmk/frabjous#87]
New version of libstrophe released.

Also I'd suggest to make some improvements:
* Remove `dev-libs/check` from dependencies, not needed since 0.9.1;
* Use tarballs instead of generated archives. Tarballs are provided since 0.9.1 and don't require autotools.

**Comment by csmk** [comment]
Sorry for the belated response, and thanks for the suggestions. The new version will be bumped shortly.
